### ISSUE TITLE
remnants after quitting

### ISSUE THREAD

**Issue by Alteus** [bugnano/rrr#6]
Left window is urxvt, right is alacritty. There are some remnants after quitting. Sometimes more lines are there.

![screenshot – 2021-06-02 07-25-14](https://user-images.githubusercontent.com/6391513/120428590-35226000-c374-11eb-82a1-c62f50379eba.png)

**Comment by bugnano** [comment]
If you try the linux console, even more lines remain from rnr.

I don't consider this a bug, just a way of how different terminals handle text user interfaces, so it is what it is.
