### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by luc-ero** [bugnano/rrr#8]
questo mi appare su due macchine diverse ma entrambe con Arch:

~ > % :rnr
Traceback (most recent call last):
  File "/usr/bin/rnr", line 5, in <module>
    from rnr.__main__ import main
ModuleNotFoundError: No module named 'rnr'
~ > % :

capisco che sia legato a pyton...

**Comment by bugnano** [comment]
Ah, le gioie delle distribuzioni rolling release😜

Questo errore è colpa di Arch, che avendo aggiornato la major release di Python, necessita une ricompilazione di tutti i pacchetti che dipendono da Python.

Quindi, la soluzione migliore per questo problema e' quella di disinstallare e reinstallare il pacchetto `rnr-fm`, dicendo al tuo AUR helper di ricompilare in modo pulito tutti i pacchetti e tutte le dipendenze (e non di usare i file di compilazione già presenti).

**Comment by luc-ero** [comment]
ti ringrazio della risposta, ho disinstallato il pacchetto e le sue
dipendenze, ho provato a scaricare il file git e lancio makepkg ma non
trova neanche le dipendenze. Provo ad installare le dipendenze una ad una
ma anche così niente...speravo. Mi sono letto il manuale di paru ma, per
mia ignoranza, non ho trovato la modalità che hai consigliato. Ti chiedo
ancora aiuto. Non sono un professionista come te ma un autodidatta che sta
imparando almeno nel mio piccolo, ti chiedo comprensione. grazie

lucio

Il giorno ven 12 mag 2023 alle ore 13:31 Franco Bugnano <
***@***.***> ha scritto:

**Comment by bugnano** [comment]
Purtroppo non conosco paru, per cui non ti so aiutare.
Io su EndeavourOS uso yay, ed i comandi sono

```bash
yay -Rs rnr-fm
```
per disinstallare `rnr-fm`, e

```bash
yay -S rnr-fm
```

per reinstallare.
Durante la reinstallazione mi chiede quali pacchetti ricompilare, e lì gli dico di ricompilare tutti.
Più di così non ti so aiutare.

**Comment by luc-ero** [comment]
ho installato yay ed in effetti la differenza salta subito all'occhio,
quest'ultimo chiede di ricompilare i pacchetti cosa che paru non fa e non
ho trovato niente nel manuale. Comunque alla fine dell'nstallazione con yay:

< ~/yay > $ :rnr


9:29
Traceback (most recent call last):
 File "/usr/bin/rnr", line 5, in <module>
   from rnr.__main__ import main
 File "/usr/lib/python3.11/site-packages/rnr/__main__.py", line 39, in
<module>
   from . import rnrview
 File "/usr/lib/python3.11/site-packages/rnr/rnrview.py", line 27, in
<module>
   from .panel import (get_file_list, sort_by_name)
 File "/usr/lib/python3.11/site-packages/rnr/panel.py", line 37, in
<module>
   from fuzzyfinder import fuzzyfinder
ModuleNotFoundError: No module named 'fuzzyfinder'
< ~/yay > $ :

questo è stato il risultato, mi dispiace molto rinunciare a rnr-fm

lucio

Il giorno sab 13 mag 2023 alle ore 07:26 Franco Bugnano <
***@***.***> ha scritto:

**Comment by bugnano** [comment]
Da qui in poi penso che te la puoi cavare da solo credo.
Come mi hai mostrato nell'output, l'errore è:
```
ModuleNotFoundError: No module named 'fuzzyfinder'
```
Questo significa che occorre fare la stessa cosa che hai fatto con `rnr-fm` col modulo `fuzzyfinder`, e così via con tutte le dipendenze che sono rimaste alla vecchia versione di Python.

**Comment by luc-ero** [comment]
E che dire... grazie tantissimo, problema risolto ma soprattutto imparato
cose nuove. Ancora grazie e sei stato gentilissimo 😊. I tuoi video sono
sempre istruttivi.

Buon fine settimana

Lucio

Il sab 13 mag 2023, 13:59 Franco Bugnano ***@***.***> ha
scritto:
